"""
Antigravity Agent - State Engine

Core infrastructure module providing:
- AgentState: The graph's memory schema
- AblyCallbackHandler: Real-time event streaming
- Redis Persistence: Checkpoint storage for pause/resume
- Graph Initialization: StateGraph builder with configuration

This module implements the "Antigravity" pattern for autonomous code generation
with human-in-the-loop approval capabilities.
"""

from __future__ import annotations

import os
import asyncio
import logging
from typing import Any, Dict, List, Optional, Sequence, TypedDict, Union
from typing_extensions import Annotated
from uuid import UUID

from dotenv import load_dotenv
from langchain_core.callbacks import AsyncCallbackHandler
from langchain_core.messages import BaseMessage
from langchain_core.outputs import GenerationChunk, ChatGenerationChunk, LLMResult
from langgraph.graph import StateGraph
from langgraph.graph.message import add_messages

# Load environment variables
load_dotenv()

# Configure logging
logger = logging.getLogger(__name__)


# =============================================================================
# Agent State Schema
# =============================================================================

class AgentState(TypedDict):
    """
    The central state schema for the Antigravity agent graph.
    
    This TypedDict serves as the graph's memory, maintaining all necessary
    context across execution steps. It supports the autonomous code generation
    workflow with human approval checkpoints.
    
    Attributes:
        manifest: The backend API definition containing endpoints, schemas,
            authentication rules, and database structure.
        user_prompt: The user's styling and frontend requirements in natural
            language.
        file_system: Virtual File System mapping file paths (e.g., "app/page.tsx")
            to their code content. This represents the generated Next.js project.
        implementation_plan: Dynamic task list generated by the planning agent,
            containing steps to fulfill the user's requirements.
        build_logs: Error logs captured from the build container, used for
            iterative debugging and fixes.
        iteration_count: Counter to prevent infinite loops during the
            build-fix cycle.
        messages: Conversational history using LangChain's message format,
            annotated with add_messages for proper reducer behavior.
        approved: Human approval status for the implementation plan.
            Set by the approval_node after interrupt resume.
        build_ready: Flag indicating successful upload to Azure Blob Storage.
            Set by the persistence_node after completing file uploads.
        build_status: Current build status from external container.
            Values: "pending", "success", "failed", "escalate"
    """
    
    manifest: Dict[str, Any]
    user_prompt: str
    file_system: Dict[str, str]
    implementation_plan: List[Dict[str, Any]]
    build_logs: List[str]
    iteration_count: int
    messages: Annotated[Sequence[BaseMessage], add_messages]
    approved: bool
    build_ready: bool
    build_status: str
    selected_template: Optional[str]
    template_files: Dict[str, str]



# =============================================================================
# Real-Time Event Bus - Ably Callback Handler
# =============================================================================

class AblyCallbackHandler(AsyncCallbackHandler):
    """
    LangChain callback handler for real-time event streaming via Ably.
    
    This handler publishes LLM tokens, tool execution status, and chain
    completion events to Ably channels, enabling real-time UI updates
    in frontend applications.
    
    Channel naming convention:
        - Token streaming: agent:stream:{thread_id}
        - Status updates: agent:status:{thread_id}
    
    Attributes:
        thread_id: Unique identifier for the current execution thread,
            used to namespace Ably channels.
        ably_client: The Ably Realtime client instance for publishing events.
    
    Example:
        >>> from ably import AblyRealtime
        >>> ably_client = AblyRealtime('your-api-key')
        >>> handler = AblyCallbackHandler(
        ...     thread_id="session-123",
        ...     ably_client=ably_client
        ... )
        >>> # Use handler in LangChain/LangGraph execution
    """
    
    def __init__(
        self,
        thread_id: str,
        ably_client: Any,  # AblyRealtime type from ably package
    ) -> None:
        """
        Initialize the Ably callback handler.
        
        Args:
            thread_id: Unique identifier for the execution thread.
            ably_client: An initialized Ably Realtime client instance.
        """
        super().__init__()
        self.thread_id = thread_id
        self.ably_client = ably_client
        self._stream_channel_name = f"agent:stream:{thread_id}"
        self._status_channel_name = f"agent:status:{thread_id}"
    
    @property
    def stream_channel(self) -> Any:
        """Get the Ably channel for token streaming."""
        return self.ably_client.channels.get(self._stream_channel_name)
    
    @property
    def status_channel(self) -> Any:
        """Get the Ably channel for status updates."""
        return self.ably_client.channels.get(self._status_channel_name)
    
    async def _publish_to_channel(
        self,
        channel: Any,
        event_name: str,
        data: Dict[str, Any],
    ) -> None:
        """
        Safely publish a message to an Ably channel.
        
        Args:
            channel: The Ably channel to publish to.
            event_name: The event name for the message.
            data: The data payload to publish.
        """
        try:
            await channel.publish(event_name, data)
        except Exception as e:
            logger.error(f"Failed to publish to Ably channel: {e}")
    
    async def on_llm_new_token(
        self,
        token: str,
        *,
        chunk: Optional[Union[GenerationChunk, ChatGenerationChunk]] = None,
        run_id: UUID,
        parent_run_id: Optional[UUID] = None,
        **kwargs: Any,
    ) -> None:
        """
        Handle new tokens from the LLM for real-time streaming.
        
        Publishes each token to the stream channel as it's generated,
        enabling character-by-character streaming in the frontend.
        
        Args:
            token: The newly generated token string.
            chunk: Optional generation chunk with additional metadata.
            run_id: Unique identifier for the current run.
            parent_run_id: Optional parent run identifier.
            **kwargs: Additional callback arguments.
        """
        await self._publish_to_channel(
            channel=self.stream_channel,
            event_name="token",
            data={
                "token": token,
                "run_id": str(run_id),
                "thread_id": self.thread_id,
            },
        )
    
    async def on_tool_start(
        self,
        serialized: Dict[str, Any],
        input_str: str,
        *,
        run_id: UUID,
        parent_run_id: Optional[UUID] = None,
        tags: Optional[List[str]] = None,
        metadata: Optional[Dict[str, Any]] = None,
        inputs: Optional[Dict[str, Any]] = None,
        **kwargs: Any,
    ) -> None:
        """
        Handle tool execution start events.
        
        Publishes a "Thinking..." status update when a tool begins execution,
        keeping the user informed about agent activity.
        
        Args:
            serialized: Serialized representation of the tool.
            input_str: String representation of the tool input.
            run_id: Unique identifier for the current run.
            parent_run_id: Optional parent run identifier.
            tags: Optional list of tags.
            metadata: Optional metadata dictionary.
            inputs: Optional inputs dictionary.
            **kwargs: Additional callback arguments.
        """
        tool_name = serialized.get("name", "unknown")
        
        await self._publish_to_channel(
            channel=self.status_channel,
            event_name="status",
            data={
                "status": "Thinking...",
                "detail": f"Executing tool: {tool_name}",
                "run_id": str(run_id),
                "thread_id": self.thread_id,
                "tool_name": tool_name,
            },
        )
    
    async def on_chain_end(
        self,
        outputs: Dict[str, Any],
        *,
        run_id: UUID,
        parent_run_id: Optional[UUID] = None,
        tags: Optional[List[str]] = None,
        **kwargs: Any,
    ) -> None:
        """
        Handle chain completion events.
        
        Publishes status updates when chains complete, such as
        "Plan Generated" or other milestone notifications.
        
        Args:
            outputs: The outputs produced by the chain.
            run_id: Unique identifier for the current run.
            parent_run_id: Optional parent run identifier.
            tags: Optional list of tags for context.
            **kwargs: Additional callback arguments.
        """
        # Determine appropriate status message based on outputs
        status_message = "Step Completed"
        
        if outputs:
            if "implementation_plan" in outputs:
                status_message = "Plan Generated"
            elif "file_system" in outputs:
                status_message = "Code Generated"
            elif "build_logs" in outputs:
                status_message = "Build Completed"
        
        await self._publish_to_channel(
            channel=self.status_channel,
            event_name="status",
            data={
                "status": status_message,
                "run_id": str(run_id),
                "thread_id": self.thread_id,
                "has_outputs": bool(outputs),
            },
        )
    
    async def on_llm_end(
        self,
        response: LLMResult,
        *,
        run_id: UUID,
        parent_run_id: Optional[UUID] = None,
        **kwargs: Any,
    ) -> None:
        """
        Handle LLM completion events.
        
        Publishes a stream-end event to signal that token streaming
        has completed for this LLM call.
        
        Args:
            response: The complete LLM response.
            run_id: Unique identifier for the current run.
            parent_run_id: Optional parent run identifier.
            **kwargs: Additional callback arguments.
        """
        await self._publish_to_channel(
            channel=self.stream_channel,
            event_name="stream_end",
            data={
                "run_id": str(run_id),
                "thread_id": self.thread_id,
            },
        )


# =============================================================================
# Persistence Layer - Redis Checkpointer
# =============================================================================

def create_redis_saver(
    redis_url: Optional[str] = None,
) -> Any:
    """
    Create and configure an AsyncRedisSaver for graph checkpointing.
    
    The Redis saver enables the "Antigravity" pattern by persisting
    graph state, allowing execution to pause for human approval and
    resume even after server restarts.
    
    Args:
        redis_url: Redis connection URL. Defaults to REDIS_URL environment
            variable if not provided.
    
    Returns:
        An AsyncRedisSaver instance configured for the graph.
    
    Raises:
        ValueError: If no Redis URL is provided or found in environment.
        ImportError: If langgraph-checkpoint-redis is not installed.
    
    Example:
        >>> saver = create_redis_saver()
        >>> # Or with explicit URL
        >>> saver = create_redis_saver("redis://localhost:6379")
    """
    # Import here to provide clear error if package not installed
    # Import here to provide clear error if package not installed
    try:
        # Try standard import path (namespace package)
        from langgraph.checkpoint.redis.aio import AsyncRedisSaver
    except ImportError:
        try:
            # Fallback to direct package import if available
            from langgraph_checkpoint_redis import AsyncRedisSaver
        except ImportError as e:
            raise ImportError(
                "langgraph-checkpoint-redis is required for Redis persistence. "
                "Install it with: pip install langgraph-checkpoint-redis"
            ) from e
    
    # Resolve Redis URL
    url = redis_url or os.getenv("REDIS_URL")
    
    if not url:
        raise ValueError(
            "Redis URL is required. Provide it as an argument or set the "
            "REDIS_URL environment variable."
        )
    
    logger.info(f"Initializing Redis checkpointer with URL: {url[:20]}...")
    
    # Create and return the async saver
    return AsyncRedisSaver.from_conn_string(url)


# =============================================================================
# Graph Initialization
# =============================================================================

def create_graph_builder(
    checkpointer: Optional[Any] = None,
) -> StateGraph:
    """
    Create and configure the StateGraph builder for the Antigravity agent.
    
    This function initializes the graph structure with the AgentState schema
    and optional Redis checkpointer. The returned builder is ready for
    node and edge definitions.
    
    Args:
        checkpointer: Optional checkpointer instance (e.g., AsyncRedisSaver)
            for state persistence. If None, the graph will run without
            persistence (useful for testing).
    
    Returns:
        A configured StateGraph instance ready for node definitions.
    
    Example:
        >>> # With Redis persistence
        >>> saver = create_redis_saver()
        >>> graph = create_graph_builder(checkpointer=saver)
        >>> 
        >>> # Define nodes
        >>> graph.add_node("planner", planner_node)
        >>> graph.add_node("coder", coder_node)
        >>> 
        >>> # Compile the graph
        >>> app = graph.compile()
    """
    # Create the graph with AgentState as the state schema
    graph = StateGraph(AgentState)
    
    logger.info("StateGraph initialized with AgentState schema")
    
    if checkpointer:
        logger.info("Checkpointer configured for state persistence")
    
    return graph


def get_graph_config(
    thread_id: str,
    recursion_limit: int = 50,
) -> Dict[str, Any]:
    """
    Generate configuration dictionary for graph execution.
    
    This configuration is passed to graph.invoke() or graph.astream()
    to control execution behavior.
    
    Args:
        thread_id: Unique identifier for the execution thread.
            This enables resume capability across sessions.
        recursion_limit: Maximum recursion depth to prevent infinite loops.
            Defaults to 50.
    
    Returns:
        Configuration dictionary for graph execution.
    
    Example:
        >>> config = get_graph_config("session-123")
        >>> result = await app.ainvoke(state, config=config)
    """
    return {
        "configurable": {
            "thread_id": thread_id,
        },
        "recursion_limit": recursion_limit,
    }


# =============================================================================
# Factory Function - Complete Setup
# =============================================================================

async def initialize_agent(
    thread_id: str,
    ably_api_key: Optional[str] = None,
    redis_url: Optional[str] = None,
) -> tuple[StateGraph, AblyCallbackHandler, Dict[str, Any]]:
    """
    Initialize all components for the Antigravity agent.
    
    This is a convenience function that sets up the complete agent
    infrastructure including the graph, callback handler, and configuration.
    
    Args:
        thread_id: Unique identifier for the execution thread.
        ably_api_key: Ably API key. Defaults to ABLY_API_KEY environment variable.
        redis_url: Redis URL. Defaults to REDIS_URL environment variable.
    
    Returns:
        A tuple containing:
            - StateGraph: The configured graph builder
            - AblyCallbackHandler: The callback handler for real-time events
            - Dict: The execution configuration
    
    Raises:
        ValueError: If required credentials are missing.
        ImportError: If required packages are not installed.
    
    Example:
        >>> graph, callback, config = await initialize_agent("session-123")
        >>> 
        >>> # Add nodes to the graph
        >>> graph.add_node("planner", planner_node)
        >>> 
        >>> # Compile and run
        >>> app = graph.compile(checkpointer=create_redis_saver())
        >>> result = await app.ainvoke(
        ...     initial_state,
        ...     config=config,
        ...     callbacks=[callback]
        ... )
    """
    # Import Ably - done here to delay import until needed
    try:
        from ably import AblyRealtime
    except ImportError as e:
        raise ImportError(
            "ably package is required for real-time events. "
            "Install it with: pip install ably"
        ) from e
    
    # Resolve Ably API key
    api_key = ably_api_key or os.getenv("ABLY_API_KEY")
    if not api_key:
        raise ValueError(
            "Ably API key is required. Provide it as an argument or set the "
            "ABLY_API_KEY environment variable."
        )
    
    # Initialize Ably client
    ably_client = AblyRealtime(api_key)
    
    # Create components
    checkpointer = create_redis_saver(redis_url)
    graph = create_graph_builder(checkpointer=checkpointer)
    callback = AblyCallbackHandler(thread_id=thread_id, ably_client=ably_client)
    config = get_graph_config(thread_id)
    
    logger.info(f"Agent initialized for thread: {thread_id}")
    
    return graph, callback, config


# =============================================================================
# Default Initial State
# =============================================================================

def get_initial_state(
    manifest: Optional[Dict[str, Any]] = None,
    user_prompt: str = "",
) -> AgentState:
    """
    Create an initial state for graph execution.
    
    Args:
        manifest: Optional backend API manifest. Defaults to empty dict.
        user_prompt: The user's frontend requirements.
    
    Returns:
        An AgentState dictionary with initialized values.
    
    Example:
        >>> state = get_initial_state(
        ...     manifest={"endpoints": [...]},
        ...     user_prompt="Create a modern dashboard with dark mode"
        ... )
    """
    return AgentState(
        manifest=manifest or {},
        user_prompt=user_prompt,
        file_system={},
        implementation_plan=[],
        build_logs=[],
        iteration_count=0,
        messages=[],
        approved=False,
        build_ready=False,
        build_status="pending",
    )
