"""
Antigravity Agent - Template Loader

This module loads the Next.js template files into the agent's file_system
so the agent can use them as a base and only generate additional files.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Dict, Optional

logger = logging.getLogger(__name__)

# Template directory relative to this file
TEMPLATE_DIR = Path(__file__).parent.parent / "templates" / "nextjs-app"


def load_template(template_name: str = "nextjs-app") -> Dict[str, str]:
    """
    Load all files from a template directory into a file_system dict.
    
    Args:
        template_name: Name of the template directory. Defaults to "nextjs-app".
    
    Returns:
        Dictionary mapping file paths to their contents.
    """
    template_path = Path(__file__).parent.parent / "templates" / template_name
    
    if not template_path.exists():
        logger.warning(f"Template directory not found: {template_path}")
        return {}
    
    file_system: Dict[str, str] = {}
    
    # Walk through all files in the template
    for file_path in template_path.rglob("*"):
        if file_path.is_file():
            # Get relative path from template root
            relative_path = str(file_path.relative_to(template_path))
            
            # Skip certain files
            if should_skip_file(relative_path):
                continue
            
            try:
                with open(file_path, "r", encoding="utf-8") as f:
                    content = f.read()
                file_system[relative_path] = content
                logger.debug(f"Loaded template file: {relative_path}")
            except Exception as e:
                logger.warning(f"Failed to read template file {relative_path}: {e}")
    
    logger.info(f"Loaded {len(file_system)} files from template '{template_name}'")
    return file_system


def should_skip_file(path: str) -> bool:
    """
    Check if a file should be skipped when loading template.
    
    Args:
        path: Relative file path.
    
    Returns:
        True if the file should be skipped.
    """
    skip_patterns = [
        "node_modules",
        ".next",
        ".git",
        "__pycache__",
        ".DS_Store",
        "package-lock.json",
        "yarn.lock",
        "pnpm-lock.yaml",
    ]
    
    return any(pattern in path for pattern in skip_patterns)


def get_template_file(file_path: str, template_name: str = "nextjs-app") -> Optional[str]:
    """
    Get a specific file from a template.
    
    Args:
        file_path: Path to the file within the template.
        template_name: Name of the template directory.
    
    Returns:
        File content or None if not found.
    """
    template_path = Path(__file__).parent.parent / "templates" / template_name / file_path
    
    if not template_path.exists():
        return None
    
    try:
        with open(template_path, "r", encoding="utf-8") as f:
            return f.read()
    except Exception as e:
        logger.warning(f"Failed to read template file {file_path}: {e}")
        return None


def list_template_files(template_name: str = "nextjs-app") -> list:
    """
    List all files in a template.
    
    Args:
        template_name: Name of the template directory.
    
    Returns:
        List of relative file paths.
    """
    template_path = Path(__file__).parent.parent / "templates" / template_name
    
    if not template_path.exists():
        return []
    
    files = []
    for file_path in template_path.rglob("*"):
        if file_path.is_file():
            relative_path = str(file_path.relative_to(template_path))
            if not should_skip_file(relative_path):
                files.append(relative_path)
    
    return sorted(files)


def merge_with_template(
    generated_files: Dict[str, str],
    template_name: str = "nextjs-app",
) -> Dict[str, str]:
    """
    Merge generated files with template files.
    
    Generated files take precedence over template files.
    
    Args:
        generated_files: Files generated by the agent.
        template_name: Name of the template to use as base.
    
    Returns:
        Merged file system with template as base.
    """
    # Start with template files
    file_system = load_template(template_name)
    
    # Override/add with generated files
    file_system.update(generated_files)
    
    logger.info(
        f"Merged {len(generated_files)} generated files with "
        f"{len(file_system) - len(generated_files)} template files"
    )
    
    return file_system


# Pre-defined template information for the planner
TEMPLATE_INFO = """
## Pre-loaded Template Files

The following files are already available from the Next.js template.
Do NOT regenerate these unless they need modification for the user's requirements:

### Configuration (DO NOT regenerate)
- package.json (Shadcn deps pre-configured)
- next.config.js
- tsconfig.json
- tailwind.config.js (Shadcn theme tokens)
- postcss.config.js (Tailwind + autoprefixer pipeline)

### Styles (DO NOT regenerate)
- styles/globals.css (CSS variables for dark/light mode)

### Utilities (DO NOT regenerate unless adding new functions)
- lib/utils.ts (cn() and helper functions)

### Shadcn UI Components (Already available - just import them)
- components/ui/button.tsx (Button with variants: default, destructive, outline, secondary, ghost, link)
- components/ui/card.tsx (Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter)
- components/ui/input.tsx (Input)
- components/ui/label.tsx (Label)
- components/ui/table.tsx (Table, TableHeader, TableBody, TableRow, TableHead, TableCell)
- components/ui/dialog.tsx (Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter)
- components/ui/badge.tsx (Badge with variants: default, secondary, destructive, outline, success, warning)
- components/ui/skeleton.tsx (Skeleton for loading states)

### Theme (DO NOT regenerate)
- components/theme-provider.tsx (ThemeProvider for dark/light mode)

### Base Layout (Modify if needed)
- app/layout.tsx (Root layout with theme provider)
- app/page.tsx (Home page - modify for user requirements)

### Server Actions Template (Extend as needed)
- lib/actions.ts (Server actions template)

### Type Definitions (Extend as needed)
- types/index.ts (Common type definitions)

## What to Generate

Only generate files that are:
1. NEW pages (app/[route]/page.tsx)
2. NEW layouts (app/[route]/layout.tsx)
3. NEW components specific to the user's requirements
4. NEW or MODIFIED server actions
5. NEW type definitions
6. MODIFICATIONS to existing files (mark as type: "modify")

## Import Paths

Use these import patterns:
- Components: import { Button } from "@/components/ui/button"
- Utils: import { cn } from "@/lib/utils"
- Actions: import { serverAction } from "@/lib/actions"
- Types: import { User } from "@/types"
"""


def get_template_context_for_planner() -> str:
    """
    Get template information to include in the planner prompt.
    
    Returns:
        String describing available template files.
    """
    return TEMPLATE_INFO
