"""
WebContainer Integration for Reflexion Loop

This module handles WebContainer build errors received from the frontend
via Ably and triggers the reflexion loop for auto-fixing.
"""

import asyncio
import json
import logging
from typing import Any, Dict, Optional

from agent.state_engine import AgentState
from agent.reflexion import reflexion_node, MAX_REFLEXION_ITERATIONS

logger = logging.getLogger(__name__)


async def handle_webcontainer_error(
    job_id: str,
    build_error_data: Dict[str, Any],
    graph: Any,
    checkpointer: Any = None,
) -> Dict[str, Any]:
    """
    Handle WebContainer build errors and trigger reflexion loop.

    This function is called when the backend receives a build error from
    the WebContainer (frontend) and forwards it via Ably. It retrieves
    the current agent state, updates it with the error logs, and triggers
    the reflexion loop to generate fixes.

    Args:
        job_id: The generation job ID (used as thread_id).
        build_error_data: Error data from WebContainer containing:
            - phase: 'install' or 'dev'
            - errors: List of error messages
            - fullOutput: Complete build output
            - orgSlug: Organization slug
            - projectSlug: Project slug
        graph: The compiled LangGraph instance.
        checkpointer: The graph checkpointer (for state retrieval).

    Returns:
        Result dictionary with success status and message.
    """
    logger.info(f"[WebContainer] Received build error for job {job_id}")
    logger.info(f"[WebContainer] Error phase: {build_error_data.get('phase')}")
    logger.info(
        f"[WebContainer] Error count: {len(build_error_data.get('errors', []))}")

    try:
        # Get current state from checkpointer
        if not checkpointer:
            logger.error("[WebContainer] No checkpointer available")
            return {"success": False, "error": "No checkpointer available"}

        config = {"configurable": {"thread_id": job_id}}

        # Retrieve current state
        state_snapshot = await checkpointer.aget(config)
        if not state_snapshot:
            logger.error(f"[WebContainer] No state found for job {job_id}")
            return {"success": False, "error": "Job state not found"}

        current_state = state_snapshot.get("channel_values", {})

        # Extract error information
        phase = build_error_data.get("phase", "unknown")
        errors = build_error_data.get("errors", [])
        full_output = build_error_data.get("fullOutput", "")

        # Format error logs
        error_logs = [
            "\n" + "="*60,
            f"WEBCONTAINER BUILD ERROR - Phase: {phase}",
            "="*60 + "\n",
        ]
        error_logs.extend(errors)
        if full_output:
            error_logs.append("\nFull Output:")
            error_logs.append(full_output)

        # Update state with build errors
        updated_state = {
            **current_state,
            "build_status": "failed",
            "build_logs": list(current_state.get("build_logs", [])) + error_logs,
        }

        # Check iteration count to prevent infinite loops
        iteration_count = current_state.get("iteration_count", 0)
        if iteration_count >= MAX_REFLEXION_ITERATIONS:
            logger.warning(
                f"[WebContainer] Max iterations ({MAX_REFLEXION_ITERATIONS}) reached, escalating"
            )
            return {
                "success": False,
                "error": "Maximum reflexion iterations reached",
                "escalate": True,
            }

        logger.info(
            f"[WebContainer] Triggering reflexion (iteration {iteration_count + 1})")

        # Invoke reflexion node to generate fixes
        reflexion_result = await reflexion_node(updated_state, config)

        # Merge reflexion result with current state
        final_state = {**updated_state, **reflexion_result}

        # Update checkpointer with new state
        await checkpointer.aput(config, final_state)

        logger.info("[WebContainer] Reflexion triggered successfully")
        logger.info(
            f"[WebContainer] Generated {len(reflexion_result.get('implementation_plan', []))} fix tasks")

        # Continue the graph execution from the generator node
        # This will apply the fixes generated by reflexion
        try:
            continuation_result = await graph.ainvoke(
                final_state,
                config=config,
            )
            logger.info("[WebContainer] Auto-fix execution completed")
            return {
                "success": True,
                "message": "Auto-fix applied successfully",
                "fixes_generated": len(reflexion_result.get('implementation_plan', [])),
            }
        except Exception as exec_error:
            logger.error(
                f"[WebContainer] Auto-fix execution failed: {exec_error}")
            return {
                "success": False,
                "error": f"Auto-fix execution failed: {str(exec_error)}",
            }

    except Exception as e:
        logger.error(
            f"[WebContainer] Error handling build error: {e}", exc_info=True)
        return {
            "success": False,
            "error": str(e),
        }


def setup_webcontainer_listener(
    ably_handler: Any,
    graph: Any,
    checkpointer: Any = None,
) -> None:
    """
    Setup Ably listener for WebContainer build errors.

    This function configures the Ably callback handler to listen for
    'build_error' events and trigger the reflexion loop.

    Args:
        ably_handler: The AblyCallbackHandler instance.
        graph: The compiled LangGraph instance.
        checkpointer: The graph checkpointer.
    """
    logger.info("[WebContainer] Setting up Ably listener for build errors")

    async def on_build_error(message_data: Dict[str, Any], job_id: str):
        """Callback for build_error events from Ably."""
        logger.info(
            f"[WebContainer] Build error event received for job {job_id}")
        result = await handle_webcontainer_error(
            job_id=job_id,
            build_error_data=message_data,
            graph=graph,
            checkpointer=checkpointer,
        )
        logger.info(f"[WebContainer] Handler result: {result}")

    # Register the callback with the Ably handler
    if hasattr(ably_handler, 'register_event_handler'):
        ably_handler.register_event_handler('build_error', on_build_error)
        logger.info("[WebContainer] Build error handler registered")
    else:
        logger.warning(
            "[WebContainer] Ably handler doesn't support event handlers")
